// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';

export function Greet(arg1:string):Promise<string>;

export function QueryGroqAPI(arg1:string):Promise<string>;

export function Scraping(arg1:string):Promise<Array<utils.Job>>;
